name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'back/Dockerfile'
      - 'back/go.*'
      - 'back/**/*.go'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64]
        # platform: [amd64, arm64]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./back
          file: ./back/Dockerfile
          platforms: linux/${{ matrix.platform }}
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  cleanup:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Clean up GHCR images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          delete-untagged: true
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_PAT }}
